### ISSUE TITLE
Hint: use the changelog to log updates

### ISSUE THREAD

**Issue by Denis-net** [j0meinaster/bracket-peek#3]
Hello @j0meinaster  ! 😊👋🏼
Congratulation for the great extension ! 👏🏼 

I was thinking about implementing it by myself, but then i stop and searched if anyone else had already crafted one,
Initially I was thinking about [hover-provider](https://code.visualstudio.com/api/references/vscode-api#HoverProvider)
Finally i came across to yours and this solution works even better.🔝

Back to the issue:
I have installed [extension-update-reporter](https://marketplace.visualstudio.com/items?itemName=ryu1kn.extension-update-reporter) that opens a changelog of changelogs when vscode restarts after extension updates.
Today it stated: "Couldn't parse the changelog. View it on Marketplace."
This is because your changelog is empty.
Please consider to move your Changelog section of the Readme.md in the Changelog.md.
In this way the issue will be fixed.

P.S. reading the known issues i read that you have issues with comments.
One of my suspended projects was about postfix templates.
In the project i faced this issue, but then i give up and focused on other projects. 
What i discovered is that with TS/JS it's possible to "tokenize" the file and get whether you are currently in a comment or not
I suggest you to take a look at the code in [vscode-postfix-ts](https://github.com/ipatalas/vscode-postfix-ts) if you want to learn more.
Another interesting project which i hadn't time to follow updates was [node-oniguruma](https://github.com/atom/node-oniguruma) that can tokenize a file.
Because the main issue is that comments and strings could potentially contain brackets and we would like to ignore them as much as possible.
Using these tools you could solve the other issue.
Good luck if you try to fight.

P.p.s I'll add references about your extension in my ([extension-workbench](https://marketplace.visualstudio.com/items?itemName=Denis-net.extension-workbench))

Best !

**Comment by j0meinaster** [comment]
Hi Denis-net, thanks for nice and supporting feedback.

I have moved the release note to CHANGELOG.md (see version: 1.1.1). Thanks for noticing.

Regarding the known issues:
While testing I noticed that brackets (and now tags aswell) in comments and strings break the algorithm of finding the correct closing bracket. I thought it was a good idead to test the extension with its own code (extension.js).. but this turned out to be a horrible idea, since especially this file is full of brackets in comments, strings and regular expressions. Even if the correct closing bracket can't be found in this scenario the extension does not crash, which is the most important.

Using this extension in our "every day" projects, me and my colleagues never feeled like this is a real issue. And atleast I am someone, who comments a lot :D

So for now I will not focus on filtering brackets from comments and strings, because this will afford additional parsing and will be really hard to implement. 

I guess the performance loss, by additional parsing, will not cover the rare use cases.

Thanks again, for your feedback and ideas.

Best wishes :)
