### ISSUE TITLE
The preview is „too wide“, it adds a horizontal scrollbar

### ISSUE THREAD

**Issue by m93a** [j0meinaster/bracket-peek#5]
## The Problem
No matter the width of the code or the size of the window, every time the extension displays “a peek”, it increases the width of the editor. This is quite annoying and makes the extension feel broken and buggy. The difference might not be noticable with a mouse, but it's a real pain for touchpad users.

## Before peek:
![image](https://user-images.githubusercontent.com/1671665/75287585-ec980080-581a-11ea-8686-663024bf4a43.png)

## After peek:
![image](https://user-images.githubusercontent.com/1671665/75287696-1d783580-581b-11ea-8e93-bdbf3e093f2f.png)

**Comment by j0meinaster** [comment]
I feel sorry, but this is the way the extensions works. I add an extra wide text decoration at the first visible line of the editor. This text decoration is showing the peek and pushing the original line content out of the view port. Which in facts adds a horizonzal scrollbar.

I don't know any other solution to put any content at top of the editor.

A possible way to avoid this would be using a tooltip on the hovered closing bracket instead of the peek at the top of the editor.

Would this help?

**Comment by m93a** [comment]
I don't have experience with writing extensions for VS Code, but can't the width of the text decoration be set explicitly? Then we could check the actual width of the string and set the decoration's width to that. If I have some free time during the weekend, I'm willing to investigate this issue further and make a PR if I figure it out.

**Comment by m93a** [comment]
Dude does the extension really work by offsetting the whole code to the right? That's pretty dumb. Whenever I try to select code by either clicking and dragging to the top of the window, or by Shift + holding Up, the editor just breaks. This extension isn't worth the trouble for me.

**Comment by j0meinaster** [comment]
Hi,

i have added customization options in 1.2.0, e.g. defining the preview location to be inline or as a tooltip on hover. The horizontal scrollbar is gone, when applying one of those settings.

Maybe you want to check the changes out?

 .. and overthink your destructive review.
